### ISSUE TITLE
Snap build regular failure on "snap refresh lxd"

### ISSUE THREAD

**Issue by g-bougard** [canonical/action-build#23]
I'm using snapcraft build action to prepare snap for [GLPI Agent](https://github.com/glpi-project/glpi-agent). 

Sometime I get an error while this build action is starting giving the following output:
```
Building Snapcraft project in "."...
Installing Snapcraft plus dependencies
  Ensuring runner is in the lxd group...
  /usr/bin/sudo groupadd --force --system lxd
  /usr/bin/sudo usermod --append --groups lxd runner
  Installing LXD...
  /usr/bin/sudo snap refresh lxd
  error: snap "lxd" has "auto-refresh" change in progress
  Error: The process '/usr/bin/sudo' failed with exit code 10
```

The last error is on that run: https://github.com/glpi-project/glpi-agent/runs/3619173369

I also got that error in the past, but it happened 2 more times yesterday and on time today. Usually I just restart the workflow and it passes, but as I'm also building other kind of packaging (rpm, deb, windows msi and MacOSX pkg) and I feel it's overkill for such a "basic" error.

Is there any work-around to by-pass such error ?

**Comment by g-bougard** [comment]
It seems there's actually an issue with the snap repository. On my own system, I can test the refresh and see:
```
[root@pc ~]# snap refresh lxd
error: cannot refresh "lxd": unexpectedly empty response from the server (try again later)
[root@pc ~]# snap refresh --list
All snaps up to date.
[root@pc ~]#
```

Maybe testing the output of `snap refresh --list` command for a lxd entry and only start `snap refresh lxd` in that case could work-around the problem. Of course, this can lead to a situation we are using a GH Actions linux image where lxd is not updated to a needed level. Personnaly I don't think this could break my builds, but having also an option to decide what to do on refresh failure may help.

**Comment by MSoegtropIMC** [comment]
I am having the same issue. There is a discussion of the LXD issue here: (https://forum.snapcraft.io/t/unexpectedly-empty-response-from-the-server/23393/14). As it looks we have to live with this for a while.

Can't one just add an `|| true` to the command - as far as I understand this it just updates and existing LXD and for most people the existing LXD is just fine.

In my CI the LXD refresh fails about 90% of the time and succeeds about 10% of the time, so an alternative option might be to just retry, but I guess if everybody does this the server issues discussed in the above link are unlikely to get better.

**Comment by sergiusens** [comment]
#24 should fix this

**Comment by sergiusens** [comment]
v1.0.9 is released and works as seen on https://github.com/snapcore/snapcraft/pull/3582/checks?check_run_id=3636816618#step:3:799

**Comment by g-bougard** [comment]
Hi @sergiusens 
thank you for the PR.

**Comment by g-bougard** [comment]
But it seems to not work in my case: https://github.com/glpi-project/glpi-agent/runs/3639683583
What could be wrong in my case ?

**Comment by MSoegtropIMC** [comment]
Thanks for the fix! I can confirm that it does work in my CI (although I have no solid statistics on this as yet).
Here is a log for a passing CI run:
(https://github.com/coq/platform/runs/3639372413?check_suite_focus=true)

**Comment by MSoegtropIMC** [comment]
@g-bougard : did you update the version? You might need an equivalent of this PR from my CI in your CI:
(https://github.com/coq/platform/pull/135/files).

**Comment by g-bougard** [comment]
Hi @MSoegtropIMC 
okay, no I did not update the version like you as I though that wasn't needed like no body told about that point. Indeed I really though the PR updated the v1.

**Comment by MSoegtropIMC** [comment]
IMHO is is bad style to change existing tags, since it could break things for other reasons (1.0.9 has other changes as well I guess). Most people expect that a tag always points to the same commit, so that one has to change the tag if one wants an updated commit. This might cause some work here and there, but the chaos of changing tags would very likely cause much more work in the long run.

**Comment by g-bougard** [comment]
Okay, I missed #25 and I guess my next build should use latest version and work.
IMHO, tags are mostly tools and I'm okay to have the "v1" tag changed to point to the latest release tag. If you need a specific version, you'll have to use the corresponding tag. Personally I expected the "v1" one always pointing to the latest version in the 1.x.y series.

**Comment by jhenstridge** [comment]
@MSoegtropIMC: we follow the recommended workflow for versioning github actions.  There is a tag for each released version of the action that is never moved, and a `v1` tag that points to the latest `v1.x.y` release.
