### ISSUE TITLE
error: cannot refresh "lxd": unexpectedly empty response from the server

### ISSUE THREAD

**Issue by casperdcl** [canonical/action-build#25]
Been happening for >24h now:

```bash
Run snapcore/action-build@v1
Building Snapcraft project in "."...
Installing Snapcraft plus dependencies
  Ensuring runner is in the lxd group...
  /usr/bin/sudo groupadd --force --system lxd
  /usr/bin/sudo usermod --append --groups lxd runner
  Installing LXD...
  /usr/bin/sudo snap refresh lxd
  error: cannot refresh "lxd": unexpectedly empty response from the server (try
         again later)
  Error: The process '/usr/bin/sudo' failed with exit code 1
```

**Comment by past-due** [comment]
While [`v1.0.9`](https://github.com/snapcore/action-build/releases/tag/v1.0.9) has been pushed with a fix for this, it looks like the [`v1`](https://github.com/snapcore/action-build/releases/tag/v1) tag is still pointing to https://github.com/snapcore/action-build/commit/6dd3202e55fccbcf8482a61f38fe630d655a2728 (i.e. `v1.0.8`).

Until someone with push / write access to this repo can update the `v1` tag to point to `v1.0.9` (@jhenstridge, @kenvandine ? - hopefully pinging the correct folks), you can manually specify the `v1.0.9` tag in your Github Actions workflow:

```diff
- uses: snapcore/action-build@v1
+ uses: snapcore/action-build@v1.0.9
```

**Comment by casperdcl** [comment]
btw I'd suggest deleting the `v1` tag and renaming `master` to `v1` https://github.com/iterative/setup-cml/pull/42#discussion_r711077808:

> The [tagging approach for actions](https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management) is very different from tags on normal repos.
>
> You need `git tag v1.x.x && git tag -f v1 && git push --tags -f`
>
> I would suggest renaming `master` to `v1` and use a hybrid of
>
> - [branch approach for actions](https://docs.github.com/en/actions/creating-actions/about-actions#using-branches-for-release-management) for major (i.e. `@v1`, `@v2`) pointers
> - tags for semver (i.e. `@v1.x.x`) pointers

**Comment by jhenstridge** [comment]
I've updated the v1 tag to point at the new v1.0.9 release Sergio made.

I strongly disagree with the idea of renaming the default branch to `v1` though: the idea of that tag is to get the latest *release* of the action: not whatever is on the tip of the branch.

**Comment by casperdcl** [comment]
@jhenstridge thanks.

P.S. GH's official docs about the [branch approach for actions](https://docs.github.com/en/actions/creating-actions/about-actions#using-branches-for-release-management) assert that branches are fine. FYI the point is to use `v1` as a *release branch*, not a *development branch*. You could use a `devel` branch instead for that.

**Comment by jhenstridge** [comment]
@casperdcl: we're currently doing something closer to the "Using tags for release management" process outlined just before in that document. That lets us tag and test a new release before updating the `v1` tag.

If we had a `v1` release branch, if we wanted to test the new release before moving everyone's workflows over we'd need to continue tagging on master and then push to the release branch afterwards. That seems just as easy to get wrong as moving the tag.
