### ISSUE TITLE
action-build doesn't build arm64 snaps

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [canonical/action-build#38]
Specifying the arm64 (and I guess any architecture other than amd64) is still building snaps for amd64

action-build doesn't seem to use the architecture.

[Here is the example](https://github.com/micro-ROS/micro-ROS-Agent/commit/b317a906dcf8f423a48a10fd82ce5415a63c151d#diff-db20462af2a3e9be94f26d4b3f31c70b06833e3f4317339eb171931e8b4a6359R22) GitHub action file using snapcore/action-build.
It's meant to build an amd64 and an arm64 snap.
But in the arm64 build we can see that the architecture is ignored and that everyhting is happening on amd64
[Complete github action log file](https://github.com/micro-ROS/micro-ROS-Agent/runs/6795292591?check_suite_focus=true)
We can see that APT is [pulling amd64 package](https://github.com/micro-ROS/micro-ROS-Agent/runs/6795292591?check_suite_focus=true#step:3:107)
And that the final snap is an [amd64 one](https://github.com/micro-ROS/micro-ROS-Agent/runs/6795292591?check_suite_focus=true#step:3:4090).

Is there a way to enable arm64 snap build on GitHub Action?

**Comment by sergiusens** [comment]
How are you setting up the ubuntu-latest instance to be an arm64 one?

FWIW, github actions run locally to the machine that was setup, it does not use the architecture entry to dispatch jobs.

To set something up that would use this, you would need to setup self hosted runners

**Comment by Guillaumebeuzeboc** [comment]
I thought
```
    strategy:
      matrix:
        architecture:
        - linux/amd64
        - linux/arm64
```
was setting up an instance for arm64.
But apparently this is just setting the variable `architecture`.
I didn't set up a self hosted runner, I thought GitHub  was supporting arm64 by default.
Since GitHub is not offering arm64 by default, this issue is irrelevant. Closing it.

**Comment by jhenstridge** [comment]
Yep. To build an arm64 snap with this action, you'd need to host your own runner.

I know @diddledani wrote [an alternative action](https://github.com/diddlesnaps/snapcraft-multiarch-action) that tries to work with the runners Github provides via qemu-user and docker, but it sounds like it might not work so well with current snapd versions.

**Comment by lucyllewy** [comment]
yes, my docker-based action is completely broken with recent snapd... I still need to dig into it but I keep procrastinating and doing something else instead.
