### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by artivis** [canonical/action-build#45]
Jobs using this action generate a deprecation warning in the form of an annotation,

```text
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

See e.g. [this workflow run](https://github.com/ubuntu-robotics/ros-snaps-examples/actions/runs/3237710895).

**Comment by jhenstridge** [comment]
This should be fixed in v1.1.1 of the action (which should be used automatically if your workflow references `snapcore/action-build@v1`).
