### ISSUE TITLE
Error installing snapcraft on arm64 runner

### ISSUE THREAD

**Issue by nurmukhametov** [canonical/action-build#60]
I am trying to build snap with action-build on self-hosted arm64 ubuntu 20.04 but it fails with the following error:

```bash
Run snapcore/action-build@v1.1.2
Building Snapcraft project in "."...
Installing Snapcraft plus dependencies
  Ensuring ubuntu is in the lxd group...
  /usr/bin/sudo groupadd --force --system lxd
  /usr/bin/sudo usermod --append --groups lxd ubuntu
  Installing LXD...
  /usr/bin/sudo snap refresh lxd
  snap "lxd" has no updates available
  Initialising LXD...
  /usr/bin/sudo lxd init --auto
  Error: The process '/usr/bin/dpkg' failed with exit code 1
```

**Comment by selfsk** [comment]
Github Runners have been updated, and switched from `moby` docker package to official ones - https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230821.1

Error seems to be coming from [`ensureLXDNetwork`](https://github.com/snapcore/action-build/blob/3457752ec9b1c79a8290b5167fce2d14df0997c1/src/tools.ts#L32). 

As a workaround
 * pin version v1.1.1
 * fork this action, remove code to checking for docker packages, run `npm all` and use your fork for github workflows
