### ISSUE TITLE
Please create a new release for compatibility with the latest runner images

### ISSUE THREAD

**Issue by lengau** [canonical/action-build#62]
It looks like these images swapped out the `docker-moby` client and server for `docker` ([20.04](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230821.1), [22.04](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230821.1)), and it's causing runs to break when setting up LXD networking ([example](https://github.com/canonical/charmcraft/actions/runs/5965402720/job/16184981782)).

~~It appears that exec.exec isn't obeying the `ignoreReturnCode` option, so instead of returning a nonzero value it's throwing an exception.~~

#59 should fix this, so theoretically the action just needs a new release.

**Comment by lengau** [comment]
Running from master appears to work: https://github.com/canonical/charmcraft/actions/runs/5966477404/job/16186184530?pr=1240

**Comment by sergiusens** [comment]
Released https://github.com/snapcore/action-build/releases/tag/v1.1.3

**Comment by max-sixty** [comment]
Hi there — the `v1` tag be updated to this? IIUC that's the GHA convention, so it'll flow through to those on `@v1`

**Comment by sergiusens** [comment]
@max-sixty it has now, please reopen if not working

**Comment by max-sixty** [comment]
Thank you!
