### ISSUE TITLE
Add dependabot configuration

### ISSUE THREAD

**Issue by gbonnefille** [canonical/action-build#63]
Once we are able to build the snap automatically, the next automation step is to update the snap automatically.
As many snap simply wrap a simple tool, checking the upstream and updating the version field will be enough to create a full automatic update process.

Does someone already has a dependabot configuration to update a snapcraft.yaml file?

**Comment by jhenstridge** [comment]
As I understand this, it'd require changes to the dependabot code base, rather than being a simple case of a configuration issue. The dependabot source can be found here if you want to contribute:

https://github.com/dependabot/dependabot-core

It isn't really in the scope of this action.
